### ISSUE TITLE
test suite https cert expired

### ISSUE THREAD

**Issue by SignpostMarv** [w3c-social/activitypump#330] opened 2018-12-07 22:01 UTC
As mentioned in #311, the cert has failed to renew.

**Comment by SignpostMarv** [comment] 2019-01-06 00:03
to clarify; the cert expired on the 6th November, but most ACME setups wouldn't be leaving things to the last minute for autorenewal.

**Comment by plehegar** [comment] 2019-07-15 15:50
https://test.activitypub.rocks/ did indeed expire. @cwebber , is that something you're familiar with? This is not a site controlled by W3C as far as I can tell.

**Comment by ap-socialhub** [comment] 2019-10-24 16:39
This issue was moved to https://socialhub.activitypub.rocks/t/test-suite-https-cert-expired/176

**Comment by ap-socialhub** [comment] 2019-10-24 19:04
This issue was moved to https://socialhub.activitypub.rocks/t/test-suite-https-cert-expired/204

**Comment by ap-socialhub** [comment] 2019-10-24 19:38
This issue was moved to https://socialhub.activitypub.rocks/t/test-suite-https-cert-expired/214

**Comment by SignpostMarv** [comment] 2019-11-18 19:01
Slowly creeping up on a year old issue now :s

If it's not feasible to get the cert sorted, is it feasible to have a w3c-owned testsuite launched somewhere?

**Comment by plehegar** [comment] 2019-11-19 22:13
@SignpostMarv , the issue is that W3C doesn't control https://test.activitypub.rocks/ as far as I know. For us to rehost again the test suite somewhere else isn't high on my list to be honest. But I'll also admit that I'm not versed enough in activity pub to comprehend the harm here. Let me launch additional inquiry around to see if I can find someone who can look into this :(

**Comment by snarfed** [comment] 2019-11-20 19:29
based on #311, looks like @cwebber owns https://test.activitypub.rocks/ . that issue had some discussion on how to stand up another instance if necessary. the source is probably https://gitlab.com/dustyweb/pubstrate/tree/master/pubstrate/aptestsuite .

**Comment by plehegar** [comment] 2019-11-20 20:03
See also https://socialhub.activitypub.rocks/t/the-activitypub-test-suite/290

**Comment by evanp** [comment] 2023-07-20 17:21
I'm going to close this in favour of #337 so we track it in one place.

**Closed as completed by evanp** 2023-07-20 17:21 UTC
