### ISSUE TITLE
Errata: Misleading note in 5.7 Likes

### ISSUE THREAD

**Issue by nightpool** [w3c-social/activitypump#349] opened 2020-05-01 11:49 UTC
In [5.7, Likes collection](https://www.w3.org/TR/activitypub/#likes), we have this informative note: (emphasis added)

> ### Note
>
> Care should be taken to not confuse the the likes collection with the similarly named but different liked collection. In sum:
>
>  - `liked`: Specifically a property of actors. This is a collection of **Like activities** performed by the actor, added to the collection as a side effect of delivery to the outbox.
>  - `likes`: May be a property of any object. This is a collection of Like activities referencing this object, added to the collection as a side effect of delivery to the inbox.

However, when this note describes the `liked` collection, it contradicts the normative definition given in [5.5](https://www.w3.org/TR/activitypub/#likes):

>  Every actor MAY have a `liked` collection. This is a list of **every object** from all of the actor’s Like activities, added as a side effect.

Which matches the definition of the side effect of Likes received in the outbox given in [6.8](https://www.w3.org/TR/activitypub/#like-activity-outbox): 

>  The side effect of receiving this in an outbox is that the server SHOULD add the object to the actor's liked Collection. 

Essentially, 5.5 and 6.8 consistently describe the `liked` collection as containing Objects, while a non-normative note in 5.7 describes the `liked` collection as containing Activities pointing to the liked objects. [This has already caused some confusion.](https://socialhub.activitypub.rocks/t/whats-actually-in-the-special-collections-causal-activity-or-target-object/651). We should publish an errata stating something like the following:

> In section 5.7, a non-normative note describes the `liked` collection as containing `Like` activities. In fact, the `liked` collections contains all of the _objects_ that the actor has `Like`d, as specified by sections 5.5 and 6.8. The note should be updated to read as follows (changes bolded):
> 
> > ### Note
> >
> > Care should be taken to not confuse the the likes collection with the similarly named but different liked collection. In sum:
> >
> >  - `liked`: Specifically a property of actors. **This is a collection of all objects from the actor's `Like` activities,** added to the collection as a side effect of delivery to the outbox.
> >  - `likes`: May be a property of any object. This is a collection of Like activities referencing this object, added to the collection as a side effect of delivery to the inbox.

Thanks to @wmurphyrd for [pointing this out on the SocialHub forums!](https://socialhub.activitypub.rocks/t/whats-actually-in-the-special-collections-causal-activity-or-target-object/651)

**Comment by cjslep** [comment] 2020-05-06 09:01
This is a dupe of #317

**Comment by evanp** [comment] 2024-05-24 16:42
This is a duplicate of #317 as @cjslep points out. However, it has a better analysis, so it's worth reading on its own. I'm going to close this in favour of the earlier issue.

**Closed as completed by evanp** 2024-05-24 16:42 UTC
