### ISSUE TITLE
Remove activity redundancy

### ISSUE THREAD

**Issue by xray7224** [w3c-social/activitypump#42] opened 2015-05-29 16:46 UTC
There is a certain amount of activity redundancy in ActivityPump. These activities are for example when a post is created you have a create/post activity:

```
{
    "@context": "http://www.w3.org/ns/activitystreams",
    "@id": "http://example.com/~alice/activity/1",
    "@type": "Create",
    "object": {
        "@type": "Note",
        "content": "Hai this is my note"
    }
}
````

For the most part the fact someone posted something and the note are not useful to distinguish, there is also the point of a note existing implies it has been created and usually notes will be populated with a `published` attribute which says the date it was indeed published.

There is a strong case for deprecating activities like these which don't offer any new information and are redundant. This would be the case for at least `create` (formally: `post`) and `share` activities.

This change would have two benefits:
1) It reduce redundancy and simply the API
2) It would also help with the convergence effort with microformats

The only benefit I can see that this brings is that if everything is wrapped in `Activity` objects it provides a consistent object you can rely on, however given that `Activity` objects are just that, objects there are already some properties we can come to expect on them and if we wanted more we could expand the attributes that object should always have, if it makes sense to do so.

**Comment by aaronpk** [comment] 2015-05-29 16:49
So would a simplified version of this request look like this?

```
{
    "@context": "http://www.w3.org/ns/activitystreams",
    "object": {
        "@id": "http://example.com/~alice/note/1",
        "@type": "Note",
        "content": "Hai this is my note"
    }
}
```

**Comment by xray7224** [comment] 2015-05-29 16:55
I was thinking the simpler version of the request could look like this:
```
{
    "@context": "http://www.w3.org/ns/activitystreams",
    "@id": "http://example.com/~alice/note/1",
    "@type": "Note",
    "content": "Hai this is my note"
}
```

**Comment by cwebber** [comment] 2015-12-12 21:31
This is a duplicate of #32.

**Closed by cwebber** 2015-12-12 21:31 UTC
