### ISSUE TITLE
No language markup in example 1 (editorial)

### ISSUE THREAD

**Issue by aphillips** [w3c-social/activitypump#128] opened 2016-10-03 23:19 UTC
https://w3c.github.io/activitypub/#obj

In Example 1 there is a document given as an example. This includes a content string (`"I'm a goat"`), but does not use any of the possible language markup values (e.g. `@language` in the context would be the simplest here). Please add that to the example.

**Comment by aphillips** [comment] 2016-10-03 23:19
This is an I18N WG comment sourced from [i18n #225](https://github.com/w3c/i18n-activity/issues/225).

Please add the `i18n` label.

**Comment by cwebber** [comment] 2016-10-04 15:56
Done.

**Comment by aphillips** [comment] 2016-10-06 17:33
Hello Social,

I18N WG just [actioned](https://www.w3.org/International/track/actions/563) me with updating this issue based on conversation in our weekly [teleconference](https://www.w3.org/2016/10/06-i18n-minutes.html#item08)

Upon further review we noticed that a number of examples contain natural language text, not just the "goat" example cited earlier. These are examples 2, 3, 6, 7, 8, 10, and 11.

Would you please examine these examples and include appropriate json-ld language markup?

**Comment by cwebber** [comment] 2016-10-12 15:30
I will update them, or at least most of them.  I'm only saying "most of them" because of the following concern:

One thing I am nervous about is that we aren't providing any reasonable way to guide users on how to "detect" when to apply what language to what item.  We talked about this at TPAC... I'm looking for some sort of guide to help servers identify when which language can be reasonably applied to which item.  Otherwise I'm afraid that users will just apply "en" to all language labels inappropriately, even if the author isn't speaking English.  (I've seen this hardcoded into html templates incorrectly, I'm sure you have as well.)  I asked if there was some document that we could point to from the i18n group to guide implementers, and I think there was an indication that someone had one privately and could reproduce it.  If we can point to that, I'd happily put `@language` in every example.  Does that make sense?  I don't want to give the impression that you should apply a `@language` field even when you don't reasonably know one to apply. 

In the meanwhile, I'll update most of them.

**Comment by aphillips** [comment] 2016-10-12 16:00
@cwebber Thanks for this. Yes, we've all seen inappropriate hardcoding. Note that it's a good idea to use different languages and language tags in examples for this reason.

We have started to develop the documentation you mentioned above. I have a [very early draft](https://www.w3.org/International/wiki/LanguageDetection) of part of it. This is [I18N ACTION 255](https://www.w3.org/International/track/actions/555). In most cases, the wiki I just linked won't apply: content that has a language tag associated with it should have that language tag chained through formats like AS2, etc.

If the language is truly unknown, it can be tagged with the tag `und`. If it is non-language content it can be tagged `zxx` (although this should not be used indiscriminately--it should be used for values that would normally be language bearing). 

A reason to omit `@language` in examples is clarity, particularly if the example is a file fragment and the language tag adds nothing. That's at editorial discretion. But generally if there is natural language data, it should be tagged somehow.

**Comment by cwebber** [comment] 2016-10-12 16:04
Great!  I added two more examples.  Now all examples where `@language` could apply except two are added.  Is the wiki page the permanent link?  (It's okay if it's in progress, as long as that link will remain the right one to point to.)  If so, I can link to it and talk about it in the appendix and I'll add it for the last two as well.

Thank you for working on that page!

**Comment by r12a** [comment] 2016-10-12 17:09
@cwebber looks like @aphillips beat me to it.  Since knowledge of the language is usually very helpful, we want language info to be available most of the time.  I think having the examples show language declarations reinforces the idea that language should be present most of the time.

Wrt to whether the right language is being used, perhaps we should add a note to the document? It could say something like this:

"It is recommended to identify the language for all natural language strings. Knowledge of the language can be important in various ways when the text is presented to a user. For example, it can allow a voice browser to change voice, or ensure that the application applies the correct font for a Japanese or Chinese user when displaying an ideographic character that appears in both languages but must look different.

"However, care should be taken to ensure that the correct language is declared, and that users do not simply apply something like `en`, regardless of the language of the text. An incorrect language declaration can cause problems."

One other  thing we could do is change example 3 (which is a simple one and won't lose meaning for the reader) to Japanese.  It could be something like the following:

```
{
  "@context": ["https://www.w3.org/ns/activitypub",
               {"@language": "ja"}],
  "type": "Person",
  "id": "https://kenzoishii.example.com/",
  "following": "https://kenzoishii.example.com/following.json",
  "followers": "https://kenzoishii.example.com/followers.json",
  "inbox": "https://kenzoishii.example.com/inbox.json",
  "outbox": "https://kenzoishii.example.com/feed.json",
  "preferredUsername": "kenzoishii",
  "name": "石井健蔵",
  "summary": "ただ例の男",
  "icon": [
    "https://kenzoishii.example.com/image/165987aklre4"
  ]
}
```

**Comment by cwebber** [comment] 2016-10-12 17:51
Okay!  I added a link to that page in 8a80764 :)

**Comment by cwebber** [comment] 2016-10-12 17:53
Ah @r12a, I added that before I read your comment.  I did call out the desirability in the new section https://w3c.github.io/activitypub/#i18n-concerns as well as linking to your wiki page.

I'm updating the last two examples now.

**Comment by cwebber** [comment] 2016-10-12 17:55
All examples have `@language` now where it can meaningfully apply, and a new section with guidance on how to reason about a `@language` is present.  Are we good to close the issue now?

**Comment by r12a** [comment] 2016-10-12 17:57
You didn't fancy using the japanese example?

**Comment by cwebber** [comment] 2016-10-12 17:58
Ah, I can include that!  Will get to it in a few. :)

**Comment by cwebber** [comment] 2016-10-12 19:41
Okay, Japanese example added!  Thanks @r12a. :)

So now all examples have `@language` where they can, we point users on how to obtain that, and we use a non-English example prominently.  Are we good now?

**Comment by aphillips** [comment] 2016-10-13 00:05
@cwebber Looks good to me. Unless @r12a has some other observation, "ship it"

As a nit, if you happened to have the file open, perhaps use the language tag 'en-GB' for examples 6 and 8 (because it illustrates that language tags can be more than just the primary language subtag). But that is totally extra credit.

**Comment by cwebber** [comment] 2016-10-13 02:42
Okay cool!  Done.  I'm closing this issue, though of course it can be reopened if @r12a has more feedback.

**Closed as completed by cwebber** 2016-10-13 02:42 UTC
Labels: Commenter Satisfied, i18n

**Comment by r12a** [comment] 2016-10-13 10:14
Good morning.  Only one suggestion: my wife says it might be better replace the Japanese phrase ただ例の男 with この方はただの例です

Otherwise, thanks for making these changes !

**Comment by cwebber** [comment] 2016-10-13 12:53
Made that change.  Thank you!

**Comment by akuckartz** [comment] 2016-10-13 19:06
For those unable to read Japanese - according to Google:
ただ例の男 = "Man of example only"
この方はただの例です = "This person is just an example"
