### ISSUE TITLE
test.activitypub.rocks is down (test data)

### ISSUE THREAD

**Issue by judgy** [w3c-social/activitypump#351] opened 2020-08-21 08:04 UTC
Maybe this is not the correct place to post, but the url for testing is not available.

**Comment by cjslep** [comment] 2020-08-21 17:25
See:
https://github.com/w3c/activitypub/issues/350
https://github.com/w3c/activitypub/issues/347
https://github.com/w3c/activitypub/issues/340
https://github.com/w3c/activitypub/issues/337

**Comment by cedricvanrompay** [comment] 2020-12-29 22:18
See https://socialhub.activitypub.rocks/t/the-activitypub-test-suite/290

**Comment by sebilasse** [comment] 2022-06-16 06:12
Yes, we informed the responsible person 4 years ago but nobody else got access to the domain.
See also https://socialhub.activitypub.rocks/t/https-test-activitypub-rocks-certifiicate-has-expired/2233/4

@cpmoser did https://github.com/yuforium/activity-streams-validator and maybe APdebug will help too:
https://socialhub.activitypub.rocks/t/student-dev-making-the-first-steps-with-activitypub-and-doing-a-video/2401/4


duplicate of 
https://github.com/w3c/activitystreams/issues/519
https://github.com/w3c/activitypub/issues/330
https://github.com/w3c/activitypub/issues/334
https://github.com/w3c/activitypub/issues/337
https://github.com/w3c/activitypub/issues/347
https://github.com/w3c/activitypub/issues/348
https://github.com/w3c/activitypub/issues/351 etc.
https://socialhub.activitypub.rocks/t/https-test-activitypub-rocks-certifiicate-has-expired/2233/4

https://github.com/go-fed/testsuite/issues/16
https://github.com/go-fed/testsuite/issues/13 etc.

related
https://github.com/w3c/activitypub/issues/335
https://github.com/w3c/activitypub/issues/321

**Comment by Timothyjchambers** [comment] 2023-07-14 19:02
So over at this mastodon group, we have organized developers to rebuild the old test suite, see this:

And here is the URl of that old test suite, rebuilt into python for easier updating or enhancing: https://github.com/steve-bate/rocks-testsuite

**Comment by evanp** [comment] 2023-07-20 17:07
I'm closing this as a duplicate in favour of #337

**Closed as completed by evanp** 2023-07-20 17:07 UTC

**Comment by ap-socialhub** [comment] 2023-09-01 15:56
This issue has been mentioned on **SocialHub**. There might be relevant details there:

https://socialhub.activitypub.rocks/t/collected-feedback-on-interop-testing-methods-living-docs-and-specs/3538/1
