### ISSUE TITLE
Test suite is broken

### ISSUE THREAD

**Issue by icco** [w3c-social/activitypump#358] opened 2022-11-12 16:42 UTC
The test suite linked in the readme, https://test.activitypub.rocks/, has an expired certificate and returns a 502 when visited.

**Comment by nightpool** [comment] 2022-11-12 17:27
the test suite in the readme only ever tested the C2S version of the spec and wasn't found to be very useful by the community, so it stopped being maintained

**Comment by rothgar** [comment] 2022-11-16 20:37
It should probably be removed from the README and spec page at https://www.w3.org/TR/activitypub/

**Comment by DeadWisdom** [comment] 2022-11-23 19:33
@nightpool -- What IS useful to the community? I'm trying to figure out how to implement ActivityPub and there doesn't seem to be anything to align to.

**Comment by mro** [comment] 2022-12-07 08:59
duplicate of #311, #330, #347, #351 etc.

There were some threads e.g. at https://socialhub.activitypub.rocks/t/help-needed-cannot-send-post-to-mastodon-inbox-verification-issue/2533/2 but in the end a test environment fails at many levels. Seems all implementors (including me) choose some arbitrary federation targets and fiddle in each case.

**Comment by ThatOneCalculator** [comment] 2023-03-10 02:24
Any update on this?

**Comment by evanp** [comment] 2023-07-20 17:07
I'm closing this as a duplicate in favour of #337

**Closed as completed by evanp** 2023-07-20 17:07 UTC

**Comment by ap-socialhub** [comment] 2023-09-01 15:56
This issue has been mentioned on **SocialHub**. There might be relevant details there:

https://socialhub.activitypub.rocks/t/collected-feedback-on-interop-testing-methods-living-docs-and-specs/3538/1

**Comment by rauschma** [comment] 2024-11-21 14:45
* Is https://feditest.org going to be a replacement for test.activitypub.rocks?
* Should the TR link to it?
